"""REnamed Strengths

Revision ID: 25825c031380
Revises: 30be3f53fb49
Create Date: 2023-09-30 12:42:34.644334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25825c031380'
down_revision = '30be3f53fb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.String(), nullable=True))
        batch_op.drop_column('Strength')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Strength', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('strength')

    # ### end Alembic commands ###
